apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: default
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
