apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: cm9vdHVzZXI=  # base64 encoded value of 'secretuser'
  DB_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 encoded value of 'secretpass'
