apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore-deployment
  labels:
    app: onlinebookstore
spec:
  replicas: 1  # Number of desired pods
  selector:
    matchLabels:
      app: onlinebookstore
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # Ensure zero downtime
      maxSurge: 1        # Allow one extra pod during the update
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
      - name: onlinebookstore
        image: 752378938230.dkr.ecr.us-west-2.amazonaws.com/onlinebookstore:55  # Your ECR image
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8083
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8083
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
      imagePullSecrets:
      - name: aws-ecr-docker-secret  # Reference to the Docker registry secret
