apiVersion: v1
kind: Service
metadata:
  name: onlinebookstore-service
  labels:
    app: onlinebookstore
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30083
    protocol: TCP
  selector:
    app: onlinebookstore
