apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-secret
  namespace: default  # Change this to your namespace if different
data:
  aws-access-key-id: QUtJQTI2TEtIUU4zT0pCSlBJRUE=
  aws-secret-access-key: Z1UvcWdmanBPbmNweHIzbWM2MENrcHVtcnNWUm1GcHM0S0Q5NVQ3Sw==
