apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore-deployment
  labels:
    app: onlinebookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinebookstore
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
      - name: onlinebookstore
        image: 752378938230.dkr.ecr.us-west-2.amazonaws.com/onlinebookstore:72
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /onlinebookstore/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /onlinebookstore/
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
      - name: aws-ecr-docker-secret
