replicaCount: 1

image:
  repository: mysql
  tag: 5.7
  pullPolicy: IfNotPresent

mysqlRootPassword: rootpassword

service:
  type: ClusterIP
  port: 3306

resources: {}

persistence:
  enabled: true
  existingClaim: mysql-pv-claim

db:
  host: mysql-server
  port: "3306"

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
