apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"efs-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"5Gi"},"csi":{"driver":"efs.csi.aws.com","volumeHandle":"fs-0c9151f8ae16fc68a"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"","volumeMode":"Filesystem"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-06-26T07:08:51Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: efs-pv
  resourceVersion: "150027"
  uid: eba1389a-8a85-4b66-bcc8-5233c65cc007
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: efs-claim
    namespace: default
    resourceVersion: "150024"
    uid: 7191eff6-994a-4178-8516-3aaf483de1e2
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9151f8ae16fc68a
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2024-06-26T07:10:35Z"
  phase: Bound
