
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    hostPathProvisionerIdentity: 01c8aceb-4ca7-47a1-adc5-4a229a446c46
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
  creationTimestamp: "2024-06-24T18:42:29Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-76eb5a4c-c233-456a-934d-6f7bb2cb43dd
  resourceVersion: "20630"
  uid: 772cada1-664b-4aa3-858a-da23c5cf44e0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pv-claim
    namespace: default
    resourceVersion: "20626"
    uid: 76eb5a4c-c233-456a-934d-6f7bb2cb43dd
  hostPath:
    path: /tmp/hostpath-provisioner/default/mysql-pv-claim
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2024-06-24T18:42:29Z"
  phase: Bound
