
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mysql-server","namespace":"default"},"spec":{"ports":[{"port":3306,"protocol":"TCP","targetPort":3306}],"selector":{"app":"mysql"}}}
  creationTimestamp: "2024-06-24T13:32:02Z"
  name: mysql-server
  namespace: default
  resourceVersion: "5428"
  uid: 71156903-e351-401f-9a63-01488fc920e1
spec:
  clusterIP: 10.111.168.198
  clusterIPs:
  - 10.111.168.198
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
